const header=document.querySelector('header');
const glow=document.querySelector('.cursor-glow');
const scrollSection=document.querySelector('.scroll-clean');
const frames=[...document.querySelectorAll('.scene-frame')];
const [dirtyFrame,midFrame,cleanFrame]=frames;
const sweep=document.querySelector('.shine-sweep');
const bar=document.querySelector('.progress i');
const percent=document.querySelector('.progress span');
const sceneSteps=[...document.querySelectorAll('.scene-steps b')];
let mx=innerWidth/2,my=innerHeight/2,gx=mx,gy=my;
addEventListener('pointermove',e=>{mx=e.clientX;my=e.clientY});
function cursorLoop(){gx+=(mx-gx)*.08;gy+=(my-gy)*.08;glow.style.left=gx+'px';glow.style.top=gy+'px';requestAnimationFrame(cursorLoop)}cursorLoop();
const smooth=(a,b,v)=>{const x=Math.max(0,Math.min(1,(v-a)/(b-a)));return x*x*(3-2*x)};
function onScroll(){
  header.classList.toggle('scrolled',scrollY>80);
  const r=scrollSection.getBoundingClientRect(),max=scrollSection.offsetHeight-innerHeight,p=Math.max(0,Math.min(1,-r.top/max)),zoom=1.025-p*.025;
  dirtyFrame.style.opacity=1-smooth(.16,.46,p);
  midFrame.style.opacity=smooth(.16,.42,p)*(1-smooth(.58,.84,p));
  cleanFrame.style.opacity=smooth(.56,.88,p);
  frames.forEach(frame=>frame.style.transform=`scale(${zoom})`);
  bar.style.width=p*100+'%';percent.textContent=Math.round(p*100)+'%';
  sweep.style.left=`calc(${p*100}% - 3px)`;sweep.style.opacity=(p>.08&&p<.92)?0.7:0;
  sceneSteps.forEach((step,i)=>step.classList.toggle('active',i===Math.min(2,Math.floor(p*3))));
  document.querySelector('.hero-bg img').style.translate=`0 ${Math.min(scrollY*.12,90)}px`;
}
addEventListener('scroll',onScroll,{passive:true});onScroll();
document.querySelectorAll('.service-grid article,.price-grid article').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${-y*3}deg) rotateY(${x*4}deg) translateY(-6px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
document.querySelector('.book form').addEventListener('submit',e=>{e.preventDefault();const toast=document.querySelector('.toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000);e.target.reset()});
document.querySelector('.menu').addEventListener('click',()=>header.classList.toggle('menu-open'));
document.querySelectorAll('header nav a').forEach(a=>a.addEventListener('click',()=>header.classList.remove('menu-open')));
[['.why .eyebrow','06 / Miért Shinecraft?'],['#reviews .eyebrow','07 / Demo értékelések'],['.pricing .eyebrow','08 / Csomagok'],['#faq .eyebrow','09 / Gyakori kérdések'],['#book .eyebrow','10 / Kapcsolat']].forEach(([selector,label])=>document.querySelector(selector).textContent=label);
document.querySelector('.hero').after(scrollSection);document.querySelector('#transform .eyebrow').textContent='01 / The transformation';document.querySelector('#services .eyebrow').textContent='02 / Szolgáltatások';document.querySelector('.demo-note')?.remove();
